<?php

namespace ContainerGkmBJlT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1gGQCkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1g_GQCk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1g_GQCk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'carouselRepository' => ['privates', 'App\\Repository\\CarouselRepository', 'getCarouselRepositoryService', true],
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', false],
            'flashMessageRepository' => ['privates', 'App\\Repository\\FlashMessageRepository', 'getFlashMessageRepositoryService', false],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', false],
            'siteConfigRepository' => ['privates', 'App\\Repository\\SiteConfigRepository', 'getSiteConfigRepositoryService', true],
        ], [
            'carouselRepository' => 'App\\Repository\\CarouselRepository',
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'flashMessageRepository' => 'App\\Repository\\FlashMessageRepository',
            'productRepository' => 'App\\Repository\\ProductRepository',
            'siteConfigRepository' => 'App\\Repository\\SiteConfigRepository',
        ]);
    }
}
