<?php

namespace ContainerGkmBJlT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0KxMvMsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0KxMvMs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0KxMvMs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fedaPayService' => ['privates', 'App\\Service\\FedaPayService', 'getFedaPayServiceService', true],
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
        ], [
            'fedaPayService' => 'App\\Service\\FedaPayService',
            'orderRepository' => 'App\\Repository\\OrderRepository',
        ]);
    }
}
