<?php

namespace ContainerGkmBJlT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarousel3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cBKSQoL.App\Entity\Carousel' shared service.
     *
     * @return \App\Entity\Carousel
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cBKSQoL": it needs an instance of "App\\Entity\\Carousel" but this type has been excluded in "config/services.yaml".');
    }
}
