<?php

namespace ContainerGkmBJlT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlashMessageAdminControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\FlashMessageAdminController' shared autowired service.
     *
     * @return \App\Controller\Admin\FlashMessageAdminController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Controller/Admin/FlashMessageAdminController.php';

        $container->services['App\\Controller\\Admin\\FlashMessageAdminController'] = $instance = new \App\Controller\Admin\FlashMessageAdminController(($container->privates['App\\Repository\\FlashMessageRepository'] ?? self::getFlashMessageRepositoryService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? self::get_ServiceLocator_O2p6Lk7Service($container))->withContext('App\\Controller\\Admin\\FlashMessageAdminController', $container));

        return $instance;
    }
}
