<?php

namespace ContainerGkmBJlT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitializeDatabaseCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\InitializeDatabaseCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\InitializeDatabaseCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:initialize-database', [], 'Initialize the database with default categories and products', false, #[\Closure(name: 'App\\Command\\InitializeDatabaseCommand')] fn (): \App\Command\InitializeDatabaseCommand => ($container->privates['App\\Command\\InitializeDatabaseCommand'] ?? $container->load('getInitializeDatabaseCommandService')));
    }
}
