<?php

namespace ContainerGkmBJlT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitializeDatabaseCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\InitializeDatabaseCommand' shared autowired service.
     *
     * @return \App\Command\InitializeDatabaseCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 5).'/src/Command/InitializeDatabaseCommand.php';

        $container->privates['App\\Command\\InitializeDatabaseCommand'] = $instance = new \App\Command\InitializeDatabaseCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:initialize-database');
        $instance->setDescription('Initialize the database with default categories and products');

        return $instance;
    }
}
