<?php

namespace ContainerGkmBJlT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLegalControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\LegalController' shared autowired service.
     *
     * @return \App\Controller\LegalController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Controller/LegalController.php';

        $container->services['App\\Controller\\LegalController'] = $instance = new \App\Controller\LegalController(($container->privates['App\\Repository\\SiteConfigRepository'] ?? $container->load('getSiteConfigRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? self::get_ServiceLocator_O2p6Lk7Service($container))->withContext('App\\Controller\\LegalController', $container));

        return $instance;
    }
}
