<?php

namespace ContainerGkmBJlT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductApiControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\ProductApiController' shared autowired service.
     *
     * @return \App\Controller\Api\ProductApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Controller/Api/ProductApiController.php';

        $container->services['App\\Controller\\Api\\ProductApiController'] = $instance = new \App\Controller\Api\ProductApiController(($container->privates['App\\Repository\\ProductRepository'] ?? self::getProductRepositoryService($container)), ($container->privates['App\\Service\\CurrencyService'] ??= new \App\Service\CurrencyService()));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? self::get_ServiceLocator_O2p6Lk7Service($container))->withContext('App\\Controller\\Api\\ProductApiController', $container));

        return $instance;
    }
}
