<?php

namespace ContainerGkmBJlT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateUserUsernameCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\UpdateUserUsernameCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\UpdateUserUsernameCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:update-user-username', [], 'Met à jour le nom d\'utilisateur d\'un utilisateur', false, #[\Closure(name: 'App\\Command\\UpdateUserUsernameCommand')] fn (): \App\Command\UpdateUserUsernameCommand => ($container->privates['App\\Command\\UpdateUserUsernameCommand'] ?? $container->load('getUpdateUserUsernameCommandService')));
    }
}
