<?php

namespace ContainerGkmBJlT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWishlistControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\WishlistController' shared autowired service.
     *
     * @return \App\Controller\WishlistController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Controller/WishlistController.php';

        $container->services['App\\Controller\\WishlistController'] = $instance = new \App\Controller\WishlistController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\WishlistRepository'] ?? self::getWishlistRepositoryService($container)), ($container->privates['App\\Repository\\ProductRepository'] ?? self::getProductRepositoryService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? self::get_ServiceLocator_O2p6Lk7Service($container))->withContext('App\\Controller\\WishlistController', $container));

        return $instance;
    }
}
