<?php

namespace ContainerK0D6iae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8kQ_9IDService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.8kQ.9ID' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8kQ.9ID'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', false],
            'emailService' => ['privates', 'App\\Service\\EmailService', 'getEmailServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'order' => ['privates', '.errored..service_locator.8kQ.9ID.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.8kQ.9ID": it needs an instance of "App\\Entity\\Order" but this type has been excluded in "config/services.yaml".'],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'emailService' => 'App\\Service\\EmailService',
            'entityManager' => '?',
            'order' => 'App\\Entity\\Order',
        ]);
    }
}
