<?php

namespace ContainerK0D6iae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateAdminUserCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\CreateAdminUserCommand' shared autowired service.
     *
     * @return \App\Command\CreateAdminUserCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\CreateAdminUserCommand'] = $instance = new \App\Command\CreateAdminUserCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setName('app:create-admin');
        $instance->setDescription('Creates an admin user automatically');

        return $instance;
    }
}
