<?php

namespace ContainerK0D6iae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckoutFormTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\CheckoutFormType' shared autowired service.
     *
     * @return \App\Form\CheckoutFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CheckoutFormType'] = new \App\Form\CheckoutFormType();
    }
}
