<?php

namespace ContainerK0D6iae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFedaPayServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\FedaPayService' shared autowired service.
     *
     * @return \App\Service\FedaPayService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\FedaPayService'] = new \App\Service\FedaPayService();
    }
}
