<?php

namespace ContainerK0D6iae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestaSitemap_DumperService extends App_KernelProdContainer
{
    /*
     * Gets the public 'presta_sitemap.dumper' shared service.
     *
     * @return \Presta\SitemapBundle\Service\Dumper
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['presta_sitemap.dumper'])) {
            return $container->services['presta_sitemap.dumper'];
        }

        $container->services['presta_sitemap.dumper'] = $instance = new \Presta\SitemapBundle\Service\Dumper($a, ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()), ($container->services['router'] ?? self::getRouterService($container)), 'sitemap', 50000);

        $instance->setDefaults($container->parameters['presta_sitemap.defaults']);

        return $instance;
    }
}
