<?php

namespace ContainerK0D6iae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestaSitemap_Eventlistener_RouteAnnotationService extends App_KernelProdContainer
{
    /*
     * Gets the private 'presta_sitemap.eventlistener.route_annotation' shared service.
     *
     * @return \Presta\SitemapBundle\EventListener\RouteAnnotationEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['presta_sitemap.eventlistener.route_annotation'])) {
            return $container->privates['presta_sitemap.eventlistener.route_annotation'];
        }

        return $container->privates['presta_sitemap.eventlistener.route_annotation'] = new \Presta\SitemapBundle\EventListener\RouteAnnotationEventListener(($container->services['router'] ?? self::getRouterService($container)), $a, 'default');
    }
}
