<?php

namespace ContainerK0D6iae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostMigrationCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\PostMigrationCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\PostMigrationCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:post-migration', [], 'Executes tasks after database migration', false, #[\Closure(name: 'App\\Command\\PostMigrationCommand')] fn (): \App\Command\PostMigrationCommand => ($container->privates['App\\Command\\PostMigrationCommand'] ?? $container->load('getPostMigrationCommandService')));
    }
}
