<?php

namespace ContainerK0D6iae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewController2Service extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ReviewController' shared autowired service.
     *
     * @return \App\Controller\ReviewController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ReviewController'] = $instance = new \App\Controller\ReviewController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? self::get_ServiceLocator_O2p6Lk7Service($container))->withContext('App\\Controller\\ReviewController', $container));

        return $instance;
    }
}
