<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJhOLM6X\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJhOLM6X/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerJhOLM6X.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerJhOLM6X\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerJhOLM6X\App_KernelDevContainer([
    'container.build_hash' => 'JhOLM6X',
    'container.build_id' => '17c50b62',
    'container.build_time' => 1751771062,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJhOLM6X');
