<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Carousel extends \App\Entity\Carousel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'subtitle', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'position', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'active', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'buttonText', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'buttonLink', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'imageFilename', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'subtitle', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'position', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'active', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'buttonText', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'buttonLink', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'imageFilename', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Carousel' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Carousel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtitle', []);

        return parent::getSubtitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtitle(?string $subtitle): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtitle', [$subtitle]);

        return parent::setSubtitle($subtitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', []);

        return parent::getPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition(int $position): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', [$position]);

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function isActive(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', []);

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(bool $active): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getButtonText(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getButtonText', []);

        return parent::getButtonText();
    }

    /**
     * {@inheritDoc}
     */
    public function setButtonText(?string $buttonText): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setButtonText', [$buttonText]);

        return parent::setButtonText($buttonText);
    }

    /**
     * {@inheritDoc}
     */
    public function getButtonLink(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getButtonLink', []);

        return parent::getButtonLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setButtonLink(?string $buttonLink): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setButtonLink', [$buttonLink]);

        return parent::setButtonLink($buttonLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFilename(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFilename', []);

        return parent::getImageFilename();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFilename(?string $imageFilename): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFilename', [$imageFilename]);

        return parent::setImageFilename($imageFilename);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile(): ?\Symfony\Component\HttpFoundation\File\File
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile(?\Symfony\Component\HttpFoundation\File\File $imageFile): \App\Entity\Carousel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$imageFile]);

        return parent::setImageFile($imageFile);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormattedUpdatedAt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormattedUpdatedAt', []);

        return parent::getFormattedUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function generateImageFileName(\Symfony\Component\String\Slugger\SluggerInterface $slugger): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generateImageFileName', [$slugger]);

        return parent::generateImageFileName($slugger);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
