<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK0D6iae\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK0D6iae/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerK0D6iae.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerK0D6iae\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerK0D6iae\App_KernelProdContainer([
    'container.build_hash' => 'K0D6iae',
    'container.build_id' => '72e38f3d',
    'container.build_time' => 1751781900,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK0D6iae');
