<?php

namespace ContainerXihxBx8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0MAs9vVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0MAs9vV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0MAs9vV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'carousel' => ['privates', '.errored..service_locator.0MAs9vV.App\\Entity\\Carousel', NULL, 'Cannot autowire service ".service_locator.0MAs9vV": it needs an instance of "App\\Entity\\Carousel" but this type has been excluded in "config/services.yaml".'],
        ], [
            'carousel' => 'App\\Entity\\Carousel',
        ]);
    }
}
