<?php

namespace ContainerXihxBx8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerUploadFixService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\AdminControllerUploadFix' shared autowired service.
     *
     * @return \App\Controller\Admin\AdminControllerUploadFix
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Controller/Admin/AdminControllerUploadFix.php';

        $container->services['App\\Controller\\Admin\\AdminControllerUploadFix'] = $instance = new \App\Controller\Admin\AdminControllerUploadFix(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? self::get_ServiceLocator_O2p6Lk7Service($container))->withContext('App\\Controller\\Admin\\AdminControllerUploadFix', $container));

        return $instance;
    }
}
