<?php

namespace ContainerXihxBx8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminCarouselControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\AdminCarouselController' shared autowired service.
     *
     * @return \App\Controller\Admin\AdminCarouselController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Controller/Admin/AdminCarouselController.php';

        $container->services['App\\Controller\\Admin\\AdminCarouselController'] = $instance = new \App\Controller\Admin\AdminCarouselController((\dirname(__DIR__, 4).'/uploads/carousel'));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? self::get_ServiceLocator_O2p6Lk7Service($container))->withContext('App\\Controller\\Admin\\AdminCarouselController', $container));

        return $instance;
    }
}
