<?php

namespace ContainerXihxBx8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarouselService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0EQ3JQ0.App\Entity\Carousel' shared service.
     *
     * @return \App\Entity\Carousel
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0EQ3JQ0": it needs an instance of "App\\Entity\\Carousel" but this type has been excluded in "config/services.yaml".');
    }
}
