<?php

namespace ContainerXihxBx8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateCategorySlugsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\GenerateCategorySlugsCommand' shared autowired service.
     *
     * @return \App\Command\GenerateCategorySlugsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 5).'/src/Command/GenerateCategorySlugsCommand.php';

        $container->privates['App\\Command\\GenerateCategorySlugsCommand'] = $instance = new \App\Command\GenerateCategorySlugsCommand(($container->privates['App\\Repository\\CategoryRepository'] ?? self::getCategoryRepositoryService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:generate-category-slugs');
        $instance->setDescription('Génère des slugs pour toutes les catégories qui n\'en ont pas.');

        return $instance;
    }
}
