<?php

namespace ContainerXihxBx8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateCategorySlugsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\GenerateCategorySlugsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\GenerateCategorySlugsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:generate-category-slugs', [], 'Génère des slugs pour toutes les catégories qui n\'en ont pas.', false, #[\Closure(name: 'App\\Command\\GenerateCategorySlugsCommand')] fn (): \App\Command\GenerateCategorySlugsCommand => ($container->privates['App\\Command\\GenerateCategorySlugsCommand'] ?? $container->load('getGenerateCategorySlugsCommandService')));
    }
}
