<?php

namespace ContainerXihxBx8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\LogoController' shared autowired service.
     *
     * @return \App\Controller\Admin\LogoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Controller/Admin/LogoController.php';

        $container->services['App\\Controller\\Admin\\LogoController'] = $instance = new \App\Controller\Admin\LogoController(($container->privates['security.helper'] ?? self::getSecurity_HelperService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? self::get_ServiceLocator_O2p6Lk7Service($container))->withContext('App\\Controller\\Admin\\LogoController', $container));

        return $instance;
    }
}
