<?php

namespace ContainerXihxBx8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateUserPasswordCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\UpdateUserPasswordCommand' shared autowired service.
     *
     * @return \App\Command\UpdateUserPasswordCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 5).'/src/Command/UpdateUserPasswordCommand.php';

        $container->privates['App\\Command\\UpdateUserPasswordCommand'] = $instance = new \App\Command\UpdateUserPasswordCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setName('app:update-user-password');
        $instance->setDescription('Met à jour le mot de passe d\'un utilisateur');

        return $instance;
    }
}
