<?php

namespace ContainerJhOLM6X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rcxgo1gService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.rcxgo1g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rcxgo1g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'flashMessage' => ['privates', '.errored..service_locator.rcxgo1g.App\\Entity\\FlashMessage', NULL, 'Cannot autowire service ".service_locator.rcxgo1g": it needs an instance of "App\\Entity\\FlashMessage" but this type has been excluded in "config/services.yaml".'],
        ], [
            'flashMessage' => 'App\\Entity\\FlashMessage',
        ]);
    }
}
