<?php

namespace ContainerJhOLM6X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CBKSQoLService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.cBKSQoL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cBKSQoL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'carousel' => ['privates', '.errored..service_locator.cBKSQoL.App\\Entity\\Carousel', NULL, 'Cannot autowire service ".service_locator.cBKSQoL": it needs an instance of "App\\Entity\\Carousel" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'carousel' => 'App\\Entity\\Carousel',
            'entityManager' => '?',
        ]);
    }
}
