<?php

namespace ContainerJhOLM6X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N8x0Q27Service extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.N8x0Q27' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N8x0Q27'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', false],
            'fedaPayService' => ['privates', 'App\\Service\\FedaPayService', 'getFedaPayServiceService', true],
            'order' => ['privates', '.errored..service_locator.N8x0Q27.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.N8x0Q27": it needs an instance of "App\\Entity\\Order" but this type has been excluded in "config/services.yaml".'],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'fedaPayService' => 'App\\Service\\FedaPayService',
            'order' => 'App\\Entity\\Order',
        ]);
    }
}
