<?php

namespace ContainerJhOLM6X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K2HbPnYService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.k2HbPnY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k2HbPnY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emailService' => ['privates', 'App\\Service\\EmailService', 'getEmailServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'fedaPayService' => ['privates', 'App\\Service\\FedaPayService', 'getFedaPayServiceService', true],
            'order' => ['privates', '.errored..service_locator.k2HbPnY.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.k2HbPnY": it needs an instance of "App\\Entity\\Order" but this type has been excluded in "config/services.yaml".'],
        ], [
            'emailService' => 'App\\Service\\EmailService',
            'entityManager' => '?',
            'fedaPayService' => 'App\\Service\\FedaPayService',
            'order' => 'App\\Entity\\Order',
        ]);
    }
}
