<?php

namespace ContainerJhOLM6X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\Admin\ConfigController' shared autowired service.
     *
     * @return \App\Controller\Admin\ConfigController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\ConfigController'] = $instance = new \App\Controller\Admin\ConfigController(($container->privates['App\\Repository\\SiteConfigRepository'] ?? $container->load('getSiteConfigRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? self::get_ServiceLocator_O2p6Lk7Service($container))->withContext('App\\Controller\\Admin\\ConfigController', $container));

        return $instance;
    }
}
