<?php

namespace ContainerJhOLM6X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlashMessageTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\FlashMessageType' shared autowired service.
     *
     * @return \App\Form\FlashMessageType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\FlashMessageType'] = new \App\Form\FlashMessageType();
    }
}
