<?php

namespace ContainerJhOLM6X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrder3Service extends App_KernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator.N8x0Q27.App\Entity\Order' shared service.
     *
     * @return \App\Entity\Order
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.N8x0Q27": it needs an instance of "App\\Entity\\Order" but this type has been excluded in "config/services.yaml".');
    }
}
