<?php

namespace ContainerJhOLM6X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileFormTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\ProfileFormType' shared autowired service.
     *
     * @return \App\Form\ProfileFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ProfileFormType'] = new \App\Form\ProfileFormType();
    }
}
