<?php

namespace ContainerJhOLM6X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSiteConfigRepositoryService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Repository\SiteConfigRepository' shared autowired service.
     *
     * @return \App\Repository\SiteConfigRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SiteConfigRepository'] = new \App\Repository\SiteConfigRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
