<?php

namespace ContainerJhOLM6X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateUserPasswordCommand_LazyService extends App_KernelDevContainer
{
    /*
     * Gets the private '.App\Command\UpdateUserPasswordCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\UpdateUserPasswordCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:update-user-password', [], 'Met à jour le mot de passe d\'un utilisateur', false, #[\Closure(name: 'App\\Command\\UpdateUserPasswordCommand')] fn (): \App\Command\UpdateUserPasswordCommand => ($container->privates['App\\Command\\UpdateUserPasswordCommand'] ?? $container->load('getUpdateUserPasswordCommandService')));
    }
}
