controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
# Redirection de /login vers /connexion pour éviter les conflits
login_redirect:
    path: /login
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /connexion
        permanent: true
