<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'sku', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'shortDescription', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'stock', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageFilename', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageName', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageFilename2', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageName2', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageFilename3', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageName3', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageFilename4', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageName4', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'sizes', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'colors', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'featured', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'isActive', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'category', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'orderItems', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'cartItems', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'reviews', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'oldPrice', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'onSale', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'discountPercentage'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'sku', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'shortDescription', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'stock', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageFilename', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageName', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageFilename2', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageName2', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageFilename3', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageName3', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageFilename4', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'imageName4', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'sizes', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'colors', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'featured', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'isActive', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'category', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'orderItems', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'cartItems', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'reviews', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'oldPrice', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'onSale', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'discountPercentage'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAtValue(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAtValue', []);

        parent::setUpdatedAtValue();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getSku(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSku', []);

        return parent::getSku();
    }

    /**
     * {@inheritDoc}
     */
    public function setSku(?string $sku): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSku', [$sku]);

        return parent::setSku($sku);
    }

    /**
     * {@inheritDoc}
     */
    public function getShortDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortDescription', []);

        return parent::getShortDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setShortDescription(?string $shortDescription): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShortDescription', [$shortDescription]);

        return parent::setShortDescription($shortDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(float $price): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getStock(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStock', []);

        return parent::getStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setStock(int $stock): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStock', [$stock]);

        return parent::setStock($stock);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFilename(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFilename', []);

        return parent::getImageFilename();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFilename(?string $imageFilename): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFilename', [$imageFilename]);

        return parent::setImageFilename($imageFilename);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageName', []);

        return parent::getImageName();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageName(?string $imageName): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageName', [$imageName]);

        return parent::setImageName($imageName);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFilename2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFilename2', []);

        return parent::getImageFilename2();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFilename2(?string $imageFilename2): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFilename2', [$imageFilename2]);

        return parent::setImageFilename2($imageFilename2);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageName2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageName2', []);

        return parent::getImageName2();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageName2(?string $imageName2): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageName2', [$imageName2]);

        return parent::setImageName2($imageName2);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFilename3(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFilename3', []);

        return parent::getImageFilename3();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFilename3(?string $imageFilename3): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFilename3', [$imageFilename3]);

        return parent::setImageFilename3($imageFilename3);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageName3(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageName3', []);

        return parent::getImageName3();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageName3(?string $imageName3): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageName3', [$imageName3]);

        return parent::setImageName3($imageName3);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFilename4(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFilename4', []);

        return parent::getImageFilename4();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFilename4(?string $imageFilename4): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFilename4', [$imageFilename4]);

        return parent::setImageFilename4($imageFilename4);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageName4(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageName4', []);

        return parent::getImageName4();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageName4(?string $imageName4): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageName4', [$imageName4]);

        return parent::setImageName4($imageName4);
    }

    /**
     * {@inheritDoc}
     */
    public function getSizes(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSizes', []);

        return parent::getSizes();
    }

    /**
     * {@inheritDoc}
     */
    public function setSizes(array $sizes): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSizes', [$sizes]);

        return parent::setSizes($sizes);
    }

    /**
     * {@inheritDoc}
     */
    public function getColors(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColors', []);

        return parent::getColors();
    }

    /**
     * {@inheritDoc}
     */
    public function setColors(array $colors): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColors', [$colors]);

        return parent::setColors($colors);
    }

    /**
     * {@inheritDoc}
     */
    public function isFeatured(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFeatured', []);

        return parent::isFeatured();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeatured(bool $featured): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeatured', [$featured]);

        return parent::setFeatured($featured);
    }

    /**
     * {@inheritDoc}
     */
    public function isIsActive(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isIsActive', []);

        return parent::isIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', []);

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive(bool $isActive): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory(): ?\App\Entity\Category
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(?\App\Entity\Category $category): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderItems(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderItems', []);

        return parent::getOrderItems();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderItem(\App\Entity\OrderItem $orderItem): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderItem', [$orderItem]);

        return parent::addOrderItem($orderItem);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrderItem(\App\Entity\OrderItem $orderItem): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrderItem', [$orderItem]);

        return parent::removeOrderItem($orderItem);
    }

    /**
     * {@inheritDoc}
     */
    public function getCartItems(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCartItems', []);

        return parent::getCartItems();
    }

    /**
     * {@inheritDoc}
     */
    public function addCartItem(\App\Entity\CartItem $cartItem): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCartItem', [$cartItem]);

        return parent::addCartItem($cartItem);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCartItem(\App\Entity\CartItem $cartItem): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCartItem', [$cartItem]);

        return parent::removeCartItem($cartItem);
    }

    /**
     * {@inheritDoc}
     */
    public function getReviews(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviews', []);

        return parent::getReviews();
    }

    /**
     * {@inheritDoc}
     */
    public function addReview(\App\Entity\Review $review): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReview', [$review]);

        return parent::addReview($review);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReview(\App\Entity\Review $review): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReview', [$review]);

        return parent::removeReview($review);
    }

    /**
     * {@inheritDoc}
     */
    public function getOldPrice(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOldPrice', []);

        return parent::getOldPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setOldPrice(?float $oldPrice): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOldPrice', [$oldPrice]);

        return parent::setOldPrice($oldPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function isOnSale(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isOnSale', []);

        return parent::isOnSale();
    }

    /**
     * {@inheritDoc}
     */
    public function setOnSale(bool $onSale): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOnSale', [$onSale]);

        return parent::setOnSale($onSale);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountPercentage(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountPercentage', []);

        return parent::getDiscountPercentage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountPercentage(?int $discountPercentage): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountPercentage', [$discountPercentage]);

        return parent::setDiscountPercentage($discountPercentage);
    }

    /**
     * {@inheritDoc}
     */
    public function calculateDiscountPercentage(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calculateDiscountPercentage', []);

        parent::calculateDiscountPercentage();
    }

}
